export type MenuCategory = 'brunch' | 'cold' | 'tea' | 'breakfast' | 'pastry';
// 'coffee' isn't listed here yet -- no local photography for it, so no
// MENU_ITEMS entry has that category. See lib/categories-data.ts's
// broader CategorySlug (all 6 real categories) for the UI category grid,
// which shows a "coming soon" tile for coffee until that changes.


export interface MenuItem {
  id: string;
  slug: string;
  labelFa: string;
  labelEn: string;
  descFa: string;
  descEn: string;
  /** Toman */
  price: number;
  popular: boolean;
  vegetarian: boolean;
  category: MenuCategory;
  /** Path relative to /public, e.g. "/images/menu/fesenjan.webp" */
  image: string;
  featured: boolean;
}

// Category display names live in lib/categories-data.ts's CATEGORY_META
// (single source of truth for real category naming) -- see that file's
// CATEGORY_META instead of a separate map here.


/**
 * Sourced directly from DivanCafe's src/lib/data.ts (the "brunch" category —
 * the only category with real, licensed local photography as of this
 * export). Keep this in sync manually if the real menu changes; there's no
 * shared package between the two repos yet.
 */
export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'loobia-polo',
    slug: 'loobia',
    labelFa: 'لوبیا پلو با گوشت',
    labelEn: 'Green Bean Rice with Beef',
    descFa: 'لوبیا سبز، گوجه‌فرنگی، گوشت چرخ‌کرده، زعفران',
    descEn: 'Green beans, tomato, ground beef, saffron',
    price: 310000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/loobia.webp',
    featured: false,
  },
  {
    id: 'khoresh-havij',
    slug: 'havij',
    labelFa: 'چلو خورشت هویج',
    labelEn: 'Carrot Stew with Rice',
    descFa: 'خورش هویج و گوشت با زعفران و لیمو عمانی',
    descEn: 'Carrot and beef stew, saffron, dried lime',
    price: 300000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/havij.webp',
    featured: false,
  },
  {
    id: 'khoresh-karafs',
    slug: 'karafs',
    labelFa: 'چلو خورشت کرفس',
    labelEn: 'Celery Stew with Rice',
    descFa: 'کرفس، گوشت، رب گوجه‌فرنگی و زردچوبه',
    descEn: 'Celery, beef, tomato paste, turmeric',
    price: 300000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/karafs.webp',
    featured: false,
  },
  {
    id: 'ferni',
    slug: 'farni',
    labelFa: 'فرنی',
    labelEn: 'Ferni (Rice Pudding)',
    descFa: 'شیر، برنج، گلاب، دارچین و پسته خلالی',
    descEn: 'Milk, rice, rosewater, cinnamon, slivered pistachio',
    price: 95000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/farni.webp',
    featured: true,
  },
  {
    id: 'khoresh-lapeh',
    slug: 'lape',
    labelFa: 'چلو خورشت لپه',
    labelEn: 'Split Pea Stew with Rice',
    descFa: 'لپه، گوشت، پیاز و دارچین',
    descEn: 'Split peas, beef, onion, cinnamon',
    price: 295000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/lape.webp',
    featured: false,
  },
  {
    id: 'khoresh-aloo-esfenaj',
    slug: 'aloo_esfenaj',
    labelFa: 'چلو خورشت آلو اسفناج',
    labelEn: 'Prune & Spinach Stew with Rice',
    descFa: 'اسفناج، آلو، گوشت و لیموترش',
    descEn: 'Spinach, prunes, beef, sour lime',
    price: 305000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/aloo_esfenaj.webp',
    featured: false,
  },
  {
    id: 'omlet-sabzijat',
    slug: 'sabzijat',
    labelFa: 'املت سبزیجات',
    labelEn: 'Vegetable Omelet',
    descFa: 'تخم‌مرغ، سبزی تازه و کمی فلفل سیاه',
    descEn: 'Eggs, fresh herbs, black pepper',
    price: 175000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/sabzijat.webp',
    featured: false,
  },
  {
    id: 'khoresh-khalal-badam',
    slug: 'khalal',
    labelFa: 'چلو خورشت خلال بادام',
    labelEn: 'Almond Sliver Stew with Rice',
    descFa: 'گوشت، خلال بادام و زعفران',
    descEn: 'Beef, slivered almonds, saffron',
    price: 330000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/khalal.webp',
    featured: false,
  },
  {
    id: 'kashk-bademjan',
    slug: 'kashk',
    labelFa: 'کشک بادمجان',
    labelEn: 'Kashk-e Bademjan',
    descFa: 'بادمجان سرخ‌شده، کشک، پیازداغ و نعناع داغ',
    descEn: 'Fried eggplant, kashk, fried onion and mint',
    price: 185000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/kashk.webp',
    featured: false,
  },
  {
    id: 'komaj',
    slug: 'komaj',
    labelFa: 'کماج',
    labelEn: 'Komaj Bread',
    descFa: 'نان سنتی جنوبی با خرما، هل و دارچین',
    descEn: 'Traditional southern bread with date, cardamom, cinnamon',
    price: 65000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/komaj.webp',
    featured: true,
  },
  {
    id: 'ash-shole-ghalamkar',
    slug: 'shole',
    labelFa: 'آش شله‌قلمکار',
    labelEn: 'Ash-e Sholeh Qalamkar',
    descFa: 'لپه، برنج، سبزی معطر و کوفته ریز',
    descEn: 'Split peas, rice, fresh herbs, tiny meatballs',
    price: 165000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/shole.webp',
    featured: false,
  },
  {
    id: 'ash-reshteh',
    slug: 'ashreshteh',
    labelFa: 'آش رشته',
    labelEn: 'Ash Reshteh',
    descFa: 'رشته، حبوبات، سبزی آش، کشک و نعناع داغ',
    descEn: 'Noodles, legumes, herbs, kashk, fried mint',
    price: 155000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/ashreshteh.webp',
    featured: true,
  },
  {
    id: 'ash-jo',
    slug: 'jo',
    labelFa: 'آش جو',
    labelEn: 'Barley Soup',
    descFa: 'جو پرک، مرغ، هویج و نعناع داغ',
    descEn: 'Pearl barley, chicken, carrot, fried mint',
    price: 145000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/jo.webp',
    featured: false,
  },
  {
    id: 'khoresh-gheimeh',
    slug: 'gheimeh',
    labelFa: 'چلو خورشت قیمه',
    labelEn: 'Gheimeh Stew with Rice',
    descFa: 'لپه، گوشت، سیب‌زمینی سرخ‌کرده و لیمو عمانی',
    descEn: 'Split peas, beef, crispy potato, dried lime',
    price: 300000,
    popular: true,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/gheimeh.webp',
    featured: false,
  },
  {
    id: 'omlet-gharch',
    slug: 'gharch',
    labelFa: 'املت قارچ',
    labelEn: 'Mushroom Omelet',
    descFa: 'تخم‌مرغ، قارچ تازه و پیاز قرمز',
    descEn: 'Eggs, fresh mushroom, red onion',
    price: 180000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/gharch.webp',
    featured: false,
  },
  {
    id: 'khoresh-fesenjan',
    slug: 'fesenjan',
    labelFa: 'چلو خورشت فسنجان',
    labelEn: 'Fesenjan Stew with Rice',
    descFa: 'مرغ، رب انار، گردو و زعفران',
    descEn: 'Chicken, pomegranate molasses, walnuts, saffron',
    price: 340000,
    popular: true,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/fesenjan.webp',
    featured: true,
  },
  {
    id: 'kalam-polo-shirazi',
    slug: 'kalampolo',
    labelFa: 'کلم پلو شیرازی',
    labelEn: 'Shirazi Cabbage Rice',
    descFa: 'برنج، کلم سفید، سبزی معطر و آلو',
    descEn: 'Rice, white cabbage, fresh herbs, dried plum',
    price: 285000,
    popular: false,
    vegetarian: true,
    category: 'brunch',
    image: '/images/menu/kalampolo.webp',
    featured: true,
  },
  {
    id: 'khoresh-aloo',
    slug: 'aloo',
    labelFa: 'چلو خورشت آلو',
    labelEn: 'Prune Stew with Rice',
    descFa: 'گوشت، آلو، خلال بادام و زعفران',
    descEn: 'Beef, prunes, slivered almonds, saffron',
    price: 315000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/aloo.webp',
    featured: false,
  },
  {
    id: 'khoresh-ghormeh-sabzi',
    slug: 'ghormeh',
    labelFa: 'چلو خورشت قورمه سبزی',
    labelEn: 'Ghormeh Sabzi Stew with Rice',
    descFa: 'سبزی قورمه، لوبیا قرمز، گوشت و لیمو عمانی',
    descEn: 'Fresh herbs, red beans, beef, dried lime',
    price: 320000,
    popular: true,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/ghormeh.webp',
    featured: true,
  },
  {
    id: 'khoresh-bamieh',
    slug: 'bamie',
    labelFa: 'چلو خورشت بامیه',
    labelEn: 'Okra Stew with Rice',
    descFa: 'بامیه، مرغ، گوجه‌فرنگی و زردچوبه',
    descEn: 'Okra, chicken, tomato, turmeric',
    price: 300000,
    popular: false,
    vegetarian: false,
    category: 'brunch',
    image: '/images/menu/bamie.webp',
    featured: false,
  },
  {
    id: 'cold-brew',
    slug: 'cold-brew',
    labelFa: 'کلد برو',
    labelEn: 'Cold Brew',
    descFa: 'دم‌آوری ۱۸ ساعته، یخ کند-آب‌شونده',
    descEn: '18-hour steep, slow-melt ice',
    price: 98000,
    popular: true,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/cold-brew.webp',
    featured: false,
  },
  {
    id: 'iced-shekar',
    slug: 'iced-shekar',
    labelFa: 'شکرقهوه یخ',
    labelEn: 'Iced Shekar Coffee',
    descFa: 'اسپرسو، شیر بادام، شکر سوخته',
    descEn: 'Espresso, almond milk, burnt sugar',
    price: 108000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/iced-shekar.webp',
    featured: false,
  },
  {
    id: 'sekanjabin-fizz',
    slug: 'sekanjabin-fizz',
    labelFa: 'سکنجبین فیز',
    labelEn: 'Sekanjabin Fizz',
    descFa: 'سکنجبین خانگی، سودا، برگ نعنا',
    descEn: 'House sekanjabin syrup, soda, mint',
    price: 88000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/sekanjabin-fizz.webp',
    featured: false,
  },
  {
    id: 'saffron-latte',
    slug: 'saffron-latte',
    labelFa: 'دمنوش زعفران و هل',
    labelEn: 'Saffron Cardamom Infusion',
    descFa: 'زعفران قاینات، هل، عسل کوهستان',
    descEn: 'Qaenat saffron, cardamom, mountain honey',
    price: 92000,
    popular: true,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/saffron-latte.webp',
    featured: false,
  },
  {
    id: 'chai-bahar',
    slug: 'chai-bahar',
    labelFa: 'چای بهارنارنج',
    labelEn: 'Bitter Orange Blossom Tea',
    descFa: 'چای لاهیجان با گلاب بهارنارنج',
    descEn: 'Lahijan black tea with orange blossom water',
    price: 70000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/chai-bahar.webp',
    featured: false,
  },
  {
    id: 'eggs-kuku',
    slug: 'eggs-kuku',
    labelFa: 'کوکو سبزی و تخم‌مرغ عسلی',
    labelEn: 'Herb Kuku & Honeyed Eggs',
    descFa: 'با نان بربری تازه و کره‌ی محلی',
    descEn: 'Served with warm barbari and local butter',
    price: 175000,
    popular: true,
    vegetarian: true,
    category: 'breakfast',
    image: '/images/menu/eggs-kuku.webp',
    featured: false,
  },
  {
    id: 'panir-sabzi',
    slug: 'panir-sabzi',
    labelFa: 'سفره‌ی پنیر و سبزی',
    labelEn: 'Cheese & Herb Spread',
    descFa: 'پنیر لیقوان، گردو، سبزی خوردن، مربای به',
    descEn: 'Lighvan cheese, walnuts, herbs, quince jam',
    price: 165000,
    popular: false,
    vegetarian: true,
    category: 'breakfast',
    image: '/images/menu/panir-sabzi.webp',
    featured: false,
  },
  {
    id: 'shakshuka',
    slug: 'shakshuka',
    labelFa: 'شکشوکای دیوان',
    labelEn: 'Divan Shakshuka',
    descFa: 'تخم‌مرغ در سس گوجه و فلفل دودی',
    descEn: 'Eggs poached in smoky pepper-tomato sauce',
    price: 195000,
    popular: false,
    vegetarian: true,
    category: 'breakfast',
    image: '/images/menu/shakshuka.webp',
    featured: false,
  },
  {
    id: 'baklava',
    slug: 'baklava',
    labelFa: 'باقلوای دیوان',
    labelEn: 'Divan Baklava',
    descFa: 'پسته اصفهان، عسل، گلاب',
    descEn: 'Isfahan pistachio, honey, rosewater',
    price: 78000,
    popular: true,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/baklava.webp',
    featured: false,
  },
  {
    id: 'saffron-croissant',
    slug: 'saffron-croissant',
    labelFa: 'کروسان زعفرانی',
    labelEn: 'Saffron Croissant',
    descFa: 'خمیر لایه‌ای با فیلینگ زعفران و خامه',
    descEn: 'Laminated dough, saffron cream filling',
    price: 95000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/saffron-croissant.webp',
    featured: false,
  },
  {
    id: 'walnut-cake',
    slug: 'walnut-cake',
    labelFa: 'کیک گردو و خرما',
    labelEn: 'Walnut Date Cake',
    descFa: 'بدون شکر تصفیه‌شده، با کارامل خرما',
    descEn: 'No refined sugar, date caramel',
    price: 85000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/walnut-cake.webp',
    featured: false,
  },
  {
    id: 'iced-americano',
    slug: 'iced-americano',
    labelFa: 'آیس آمریکانو',
    labelEn: 'Iced Americano',
    descFa: 'اسپرسو، آب سرد، یخ',
    descEn: 'Espresso, cold water, ice',
    price: 78000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/iced-americano.webp',
    featured: false,
  },
  {
    id: 'iced-latte',
    slug: 'iced-latte',
    labelFa: 'آیس لاته',
    labelEn: 'Iced Latte',
    descFa: 'اسپرسو، شیر سرد، یخ',
    descEn: 'Espresso, cold milk, ice',
    price: 102000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/iced-latte.webp',
    featured: false,
  },
  {
    id: 'iced-mocha',
    slug: 'iced-mocha',
    labelFa: 'آیس موکا',
    labelEn: 'Iced Mocha',
    descFa: 'اسپرسو، شیر سرد، شکلات، یخ',
    descEn: 'Espresso, cold milk, chocolate, ice',
    price: 112000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/iced-mocha.webp',
    featured: false,
  },
  {
    id: 'frappuccino',
    slug: 'frappuccino',
    labelFa: 'فراپوچینو',
    labelEn: 'Frappuccino',
    descFa: 'اسپرسو یخ‌زده، شیر، خامه',
    descEn: 'Blended iced espresso, milk, cream',
    price: 118000,
    popular: true,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/frappuccino.webp',
    featured: false,
  },
  {
    id: 'caramel-frappuccino',
    slug: 'caramel-frappuccino',
    labelFa: 'فراپوچینو کارامل',
    labelEn: 'Caramel Frappuccino',
    descFa: 'اسپرسو یخ‌زده، شیر، سس کارامل، خامه',
    descEn: 'Blended iced espresso, milk, caramel, cream',
    price: 122000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/caramel-frappuccino.webp',
    featured: false,
  },
  {
    id: 'lemonade',
    slug: 'lemonade',
    labelFa: 'لیموناد خانگی',
    labelEn: 'House Lemonade',
    descFa: 'لیمو تازه، نعنا، شربت',
    descEn: 'Fresh lemon, mint, syrup',
    price: 82000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/lemonade.webp',
    featured: false,
  },
  {
    id: 'iced-tea-fresh',
    slug: 'iced-tea-fresh',
    labelFa: 'آیس تی',
    labelEn: 'Iced Tea',
    descFa: 'چای سیاه، لیمو، یخ',
    descEn: 'Black tea, lemon, ice',
    price: 76000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/iced-tea-fresh.webp',
    featured: false,
  },
  {
    id: 'berry-smoothie',
    slug: 'berry-smoothie',
    labelFa: 'اسموتی توت‌های وحشی',
    labelEn: 'Mixed Berry Smoothie',
    descFa: 'توت‌فرنگی، ماست، عسل',
    descEn: 'Strawberry, yogurt, honey',
    price: 105000,
    popular: false,
    vegetarian: true,
    category: 'cold',
    image: '/images/menu/berry-smoothie.webp',
    featured: false,
  },
  {
    id: 'black-tea',
    slug: 'black-tea',
    labelFa: 'چای سیاه',
    labelEn: 'Black Tea',
    descFa: 'برگ چای سیاه درجه یک',
    descEn: 'Premium black tea leaves',
    price: 62000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/black-tea.webp',
    featured: false,
  },
  {
    id: 'green-tea',
    slug: 'green-tea',
    labelFa: 'چای سبز',
    labelEn: 'Green Tea',
    descFa: 'برگ چای سبز ژاپنی',
    descEn: 'Japanese green tea leaves',
    price: 65000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/green-tea.webp',
    featured: false,
  },
  {
    id: 'chamomile-tea',
    slug: 'chamomile-tea',
    labelFa: 'دمنوش بابونه',
    labelEn: 'Chamomile Infusion',
    descFa: 'گل بابونه خشک',
    descEn: 'Dried chamomile flowers',
    price: 68000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/chamomile-tea.webp',
    featured: false,
  },
  {
    id: 'mint-tea',
    slug: 'mint-tea',
    labelFa: 'دمنوش نعنا',
    labelEn: 'Mint Infusion',
    descFa: 'برگ نعنای تازه، عسل',
    descEn: 'Fresh mint leaves, honey',
    price: 68000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/mint-tea.webp',
    featured: false,
  },
  {
    id: 'hibiscus-tea',
    slug: 'hibiscus-tea',
    labelFa: 'دمنوش چای ترش',
    labelEn: 'Hibiscus Tea',
    descFa: 'گلبرگ ترش، دارچین',
    descEn: 'Dried hibiscus petals, cinnamon',
    price: 72000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/hibiscus-tea.webp',
    featured: false,
  },
  {
    id: 'ginger-lemon-tea',
    slug: 'ginger-lemon-tea',
    labelFa: 'دمنوش زنجبیل و لیمو',
    labelEn: 'Ginger Lemon Tea',
    descFa: 'زنجبیل تازه، لیمو، عسل',
    descEn: 'Fresh ginger, lemon, honey',
    price: 75000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/ginger-lemon-tea.webp',
    featured: false,
  },
  {
    id: 'masala-chai',
    slug: 'masala-chai',
    labelFa: 'چای ماسالای هندی',
    labelEn: 'Masala Chai',
    descFa: 'چای سیاه، دارچین، هل، شیر',
    descEn: 'Black tea, cinnamon, cardamom, milk',
    price: 85000,
    popular: false,
    vegetarian: true,
    category: 'tea',
    image: '/images/menu/masala-chai.webp',
    featured: false,
  },
  {
    id: 'tiramisu',
    slug: 'tiramisu',
    labelFa: 'تیرامیسو',
    labelEn: 'Tiramisu',
    descFa: 'ماسکارپونه، قهوه، بیسکویت لیدی‌فینگر، کاکائو',
    descEn: 'Mascarpone, espresso, ladyfingers, cocoa',
    price: 115000,
    popular: true,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/tiramisu.webp',
    featured: false,
  },
  {
    id: 'cheesecake',
    slug: 'cheesecake',
    labelFa: 'چیزکیک نیویورکی',
    labelEn: 'New York Cheesecake',
    descFa: 'پنیر خامه‌ای، بیسکویت، سس توت',
    descEn: 'Cream cheese, biscuit base, berry sauce',
    price: 110000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/cheesecake.webp',
    featured: false,
  },
  {
    id: 'brownie',
    slug: 'brownie',
    labelFa: 'براونی شکلاتی',
    labelEn: 'Chocolate Brownie',
    descFa: 'شکلات تلخ، گردو، کره',
    descEn: 'Dark chocolate, walnuts, butter',
    price: 88000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/brownie.webp',
    featured: false,
  },
  {
    id: 'carrot-cake',
    slug: 'carrot-cake',
    labelFa: 'کیک هویج',
    labelEn: 'Carrot Cake',
    descFa: 'هویج، گردو، دارچین، خامه پنیر',
    descEn: 'Carrot, walnuts, cinnamon, cream-cheese frosting',
    price: 95000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/carrot-cake.webp',
    featured: false,
  },
  {
    id: 'lemon-tart',
    slug: 'lemon-tart',
    labelFa: 'تارت لیمو با مرنگ',
    labelEn: 'Lemon Meringue Tart',
    descFa: 'کرم لیمو، مرنگ، خمیر شکری',
    descEn: 'Lemon curd, torched meringue, shortcrust',
    price: 98000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/lemon-tart.webp',
    featured: false,
  },
  {
    id: 'panna-cotta',
    slug: 'panna-cotta',
    labelFa: 'پاناکوتا با سس توت',
    labelEn: 'Panna Cotta',
    descFa: 'خامه، وانیل، سس توت قرمز',
    descEn: 'Cream, vanilla, red berry sauce',
    price: 92000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/panna-cotta.webp',
    featured: false,
  },
  {
    id: 'macarons',
    slug: 'macarons',
    labelFa: 'ماکارون فرانسوی',
    labelEn: 'French Macarons',
    descFa: 'بادام، سفیده تخم‌مرغ، کرم داخلی',
    descEn: 'Almond flour, egg white, buttercream filling',
    price: 85000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/macarons.webp',
    featured: false,
  },
  {
    id: 'chocolate-lava-cake',
    slug: 'chocolate-lava-cake',
    labelFa: 'کیک لاوا شکلاتی',
    labelEn: 'Chocolate Lava Cake',
    descFa: 'شکلات تلخ، کره، هسته‌ی مذاب',
    descEn: 'Dark chocolate, butter, molten center',
    price: 118000,
    popular: true,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/chocolate-lava-cake.webp',
    featured: false,
  },
  {
    id: 'waffle',
    slug: 'waffle',
    labelFa: 'وافل با میوه و بستنی',
    labelEn: 'Waffle with Fruit & Ice Cream',
    descFa: 'خمیر وافل، توت‌های تازه، بستنی وانیل',
    descEn: 'Waffle batter, fresh berries, vanilla ice cream',
    price: 125000,
    popular: false,
    vegetarian: true,
    category: 'pastry',
    image: '/images/menu/waffle.webp',
    featured: false,
  },
];


export function getFeaturedItems(items: MenuItem[] = MENU_ITEMS): MenuItem[] {
  return items.filter((item) => item.featured);
}

export function getItemsByCategory(
  items: MenuItem[] = MENU_ITEMS
): Record<MenuCategory, MenuItem[]> {
  const grouped = {} as Record<MenuCategory, MenuItem[]>;
  for (const item of items) {
    if (!grouped[item.category]) grouped[item.category] = [];
    grouped[item.category].push(item);
  }
  return grouped;
}

export function findMenuItemBySlug(
  slug: string,
  items: MenuItem[] = MENU_ITEMS
): MenuItem | undefined {
  return items.find((item) => item.slug === slug);
}

/** Formats a Toman price the way DivanCafe's own ledger/ticket UI does. */
export function formatToman(price: number, locale: 'fa' | 'en' = 'fa'): string {
  const formatted = new Intl.NumberFormat(locale === 'fa' ? 'fa-IR' : 'en-US').format(price);
  return locale === 'fa' ? `${formatted} تومان` : `${formatted} Toman`;
}
